import { parseActionIntent } from '../js/actions/local-actions.js';
let p=0,f=0;
const chk=(txt,want)=>{ const r=parseActionIntent(txt);
  const got = r ? (r.type==='open_app'?`open_app:${r.app}`: r.type==='media'?`media:${r.action}`:
                   r.type==='volume'?`volume:${r.level}`: r.type==='search'?`search:${r.engine}`: r.type) : 'null';
  const ok = got===want;
  ok?p++:f++;
  console.log(`  ${ok?'\x1b[32m✓\x1b[0m':'\x1b[31m✗\x1b[0m'} "${txt}" → ${got}${ok?'':`  (want ${want})`}`);
};
console.log('\n▸ APP LAUNCH');
chk('open whatsapp','open_app:whatsapp');
chk('Open WhatsApp','open_app:whatsapp');
chk('launch spotify','open_app:spotify');
chk('start vs code','open_app:vscode');
chk('fire up the terminal','open_app:terminal');
chk('open my editor','open_app:vscode');
chk('go to youtube','open_app:youtube');
chk('bring up the calculator','open_app:calculator');
chk('open telegram','open_app:telegram');
console.log('\n▸ MEDIA + VOLUME');
chk('play music','media:playpause');
chk('pause','media:playpause');
chk('next song','media:next');
chk('volume 40','volume:40');
chk('volume up','volume:up');
chk('mute','volume:mute');
console.log('\n▸ WEB');
chk('search for quantum tunnelling','search:duckduckgo');
chk('play lofi beats on youtube','search:youtube');
chk('open github.com','open_app:github');   // app entry wins over raw URL — correct
chk('open example.org','open_url');
console.log('\n▸ MUST NOT HIJACK (these belong to chat/UI)');
chk('open the camera','null');
chk('what is 2+2','null');
chk('explain recursion','null');
chk('mute your voice','null');
chk('open the chat panel','null');
chk('what did i just say','null');
chk('hello','null');
chk('can you open up about your architecture','null');
console.log(`\n  PASS ${p}  FAIL ${f}`);
process.exit(f?1:0);
